version: '3.3'

networks:
  backend:

services:
  web:
    build: 
      context: .
      dockerfile: ./web/Dockerfile
    container_name: django_photo_gallery
    env_file: 
      - ./common.env
    command: ./src/manage.py runserver 0:8000
    restart: on-failure
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - backend
    depends_on:
      - db

  db:
    image: postgres:latest
    # build: 
    #   context: .
    #   dockerfile: ./db/Dockerfile
    container_name: db_photo_gallery
    env_file: 
      - ./common.env
    networks:
      - backend
    volumes:
      - /dbdata:/dbdata
